[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
core = { path = "../core" }
typer = { path = "../typer", optional = true }
mathwiz = { path = "../mathwiz", optional = true }
sciencewiz = { path = "../sciencewiz", optional = true }
customwiz = { path = "../customwiz", optional = true }

[features]
default = ["typer", "mathwiz", "sciencewiz", "customwiz"]
typer = ["dep:typer"]
mathwiz = ["dep:mathwiz"]
sciencewiz = ["dep:sciencewiz"]
customwiz = ["dep:customwiz"]